name: Basic Test
on: [push]
jobs:
  Basic Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create test file using script
        run: ./test-files-creator.sh -c=1 -s=1000 -o=dir -h=sha256 --csv
      - name: Confirm that file is created
        run: if [ $(find dir/* | wc -l) -ne 1 ]; then exit 1; fi
      - name: Check file hash
        run: |
            export saved_hash=$(cat log.csv | awk -F';' '{printf "%s", $5}')
            echo $saved_hash dir/$(ls dir) | sha256sum --check
